// Database types for Supabase
// These are simplified types - full types would be generated by Supabase CLI

export interface Database {
    public: {
        Tables: {
            recipes: {
                Row: RecipeRow;
                Insert: Omit<RecipeRow, 'id' | 'created_at' | 'average_rating' | 'rating_count' | 'view_count'>;
                Update: Partial<RecipeRow>;
            };
            recipe_comments: {
                Row: RecipeCommentRow;
                Insert: Omit<RecipeCommentRow, 'id' | 'created_at' | 'updated_at'>;
                Update: Partial<RecipeCommentRow>;
            };
            recipe_ratings: {
                Row: RecipeRatingRow;
                Insert: Omit<RecipeRatingRow, 'id' | 'created_at'>;
                Update: Partial<RecipeRatingRow>;
            };
            saved_recipes: {
                Row: SavedRecipeRow;
                Insert: Omit<SavedRecipeRow, 'saved_at'>;
                Update: Partial<SavedRecipeRow>;
            };
            recipe_collections: {
                Row: RecipeCollectionRow;
                Insert: Omit<RecipeCollectionRow, 'id' | 'created_at' | 'updated_at'>;
                Update: Partial<RecipeCollectionRow>;
            };
            collection_recipes: {
                Row: CollectionRecipeRow;
                Insert: CollectionRecipeRow;
                Update: Partial<CollectionRecipeRow>;
            };
            users: {
                Row: UserRow;
                Insert: Omit<UserRow, 'created_at' | 'updated_at'>;
                Update: Partial<UserRow>;
            };
            creator_follows: {
                Row: CreatorFollowRow;
                Insert: Omit<CreatorFollowRow, 'created_at'>;
                Update: Partial<CreatorFollowRow>;
            };
        };
    };
}

export interface RecipeRow {
    id: string;
    name: string;
    description: string;
    image_url: string;
    prep_time_minutes: number;
    cook_time_minutes: number;
    default_servings: number;
    ingredients: IngredientData[];
    instructions: string[];
    author_id: string;
    author_name: string;
    author_avatar_url: string | null;
    created_at: string;
    average_rating: number;
    rating_count: number;
    view_count: number;
    labels: string[];
    language: string;
    nutrition: NutritionData | null;
}

export interface IngredientData {
    name: string;
    amount: number;
    unit: string;
}

export interface NutritionData {
    calories?: number;
    protein_g?: number;
    carbs_g?: number;
    fat_g?: number;
    fiber_g?: number;
    sugar_g?: number;
    sodium_mg?: number;
}

export interface RecipeCommentRow {
    id: string;
    recipe_id: string;
    user_id: string;
    comment: string;
    created_at: string;
    updated_at: string;
}

export interface RecipeRatingRow {
    id: string;
    recipe_id: string;
    user_id: string;
    rating: number;
    created_at: string;
}

export interface SavedRecipeRow {
    user_id: string;
    recipe_id: string;
    saved_at: string;
}

export interface RecipeCollectionRow {
    id: string;
    name: string;
    name_de: string | null;
    description: string | null;
    description_de: string | null;
    image_url: string | null;
    icon: string;
    is_featured: boolean;
    display_order: number;
    created_at: string;
    updated_at: string;
}

export interface CollectionRecipeRow {
    collection_id: string;
    recipe_id: string;
    display_order: number;
    added_at: string;
}

export interface UserRow {
    id: string;
    email: string;
    display_name: string | null;
    avatar_url: string | null;
    auth_provider: string | null;
    created_at: string;
    updated_at: string;
}

export interface CreatorFollowRow {
    follower_id: string;
    creator_id: string;
    created_at: string;
}
